version: "3.8"
services:
  server:
    build:
      dockerfile: Dockerfile.server
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://db:27017/chat-app

  client:
    build:
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
  db:
    image: mongo:6.0.2
    ports:
      - "27017:27017"
    container_name: db_chat-app
    volumes:
      - /data/db
