name: CI
on:
  pull_request:
    branches: ["main"]
jobs:
  eslint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository on GITHUB_WORKSPACE
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: npm install
      - name: Running ESLint on client
        run: |
          cd packages/client
          npm run eslint
      - name: Running ESLint on server
        run: |
          cd packages/server
          npm run eslint
      - run: echo "${{job.name}} job status ${{ job.status }}."
